version: 2

updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
      commit-message:
          prefix: "chore"
          include: "scope"

    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
      cooldown:
          default-days: 7
      commit-message:
          prefix: "chore"
          include: "scope"
      groups:
          # Group minor+patch npm updates together; major & security stay separate
          minor-updates:
              applies-to: "version-updates"
              update-types:
                  - "patch"
                  - "minor"
