// Base oxlint configuration shared between oxlint.config.ts and eslint.config.js.
// env, settings, and ignorePatterns are intentionally omitted here:
// eslint-plugin-oxlint's buildFromOxlintConfig uses only plugins/categories/rules
// to determine which ESLint rules to disable.

/** @type {import("oxlint").OxlintConfig} */
export const oxlintBaseConfig = {
    plugins: [],
    // The correctness category is disabled globally so that only the rules
    // explicitly listed in the overrides below are active. This avoids enabling
    // the full default correctness rule set for non-TypeScript files (of which
    // there are none in this project) and makes the active rule set explicit.
    categories: {
        correctness: "off",
    },
    ignorePatterns: ["dist", "src/routeTree.gen.ts"],
    overrides: [
        {
            files: ["**/*.{ts,tsx}"],
            plugins: ["typescript", "react"],
            rules: {
                "constructor-super": "off",
                "for-direction": "error",
                "no-async-promise-executor": "error",
                "no-case-declarations": "error",
                "no-class-assign": "off",
                "no-compare-neg-zero": "error",
                "no-cond-assign": "error",
                "no-const-assign": "off",
                "no-constant-binary-expression": "error",
                "no-constant-condition": "error",
                "no-control-regex": "error",
                "no-debugger": "error",
                "no-delete-var": "error",
                "no-dupe-class-members": "off",
                "no-dupe-else-if": "error",
                "no-dupe-keys": "off",
                "no-duplicate-case": "error",
                "no-empty": "error",
                "no-empty-character-class": "error",
                "no-empty-pattern": "error",
                "no-empty-static-block": "error",
                "no-ex-assign": "error",
                "no-extra-boolean-cast": "error",
                "no-fallthrough": "error",
                "no-func-assign": "off",
                "no-global-assign": "error",
                "no-import-assign": "off",
                "no-invalid-regexp": "error",
                "no-irregular-whitespace": "error",
                "no-loss-of-precision": "error",
                "no-misleading-character-class": "error",
                "no-new-native-nonconstructor": "off",
                "no-nonoctal-decimal-escape": "error",
                "no-obj-calls": "off",
                "no-prototype-builtins": "error",
                "no-redeclare": "off",
                "no-regex-spaces": "error",
                "no-self-assign": "error",
                "no-setter-return": "off",
                "no-shadow-restricted-names": "error",
                "no-sparse-arrays": "error",
                "no-this-before-super": "off",
                "no-unexpected-multiline": "error",
                "no-unsafe-finally": "error",
                "no-unsafe-negation": "off",
                "no-unsafe-optional-chaining": "error",
                "no-unused-labels": "error",
                "no-unused-private-class-members": "error",
                "no-unused-vars": "error",
                "no-useless-backreference": "error",
                "no-useless-catch": "error",
                "no-useless-escape": "error",
                "no-with": "off",
                "require-yield": "error",
                "use-isnan": "error",
                "valid-typeof": "error",
                "no-var": "error",
                "prefer-const": "error",
                "prefer-rest-params": "error",
                "prefer-spread": "error",
                "@typescript-eslint/ban-ts-comment": [
                    "error",
                    { minimumDescriptionLength: 10 },
                ],
                "no-array-constructor": "error",
                "@typescript-eslint/no-duplicate-enum-values": "error",
                "@typescript-eslint/no-dynamic-delete": "error",
                "@typescript-eslint/no-empty-object-type": "error",
                "@typescript-eslint/no-explicit-any": "error",
                "@typescript-eslint/no-extra-non-null-assertion": "error",
                "@typescript-eslint/no-extraneous-class": "error",
                "@typescript-eslint/no-invalid-void-type": "error",
                "@typescript-eslint/no-misused-new": "error",
                "@typescript-eslint/no-namespace": "error",
                "@typescript-eslint/no-non-null-asserted-nullish-coalescing":
                    "error",
                "@typescript-eslint/no-non-null-asserted-optional-chain":
                    "error",
                "@typescript-eslint/no-non-null-assertion": "error",
                "@typescript-eslint/no-require-imports": "error",
                "@typescript-eslint/no-this-alias": "error",
                "@typescript-eslint/no-unnecessary-type-constraint": "error",
                "@typescript-eslint/no-unsafe-declaration-merging": "error",
                "@typescript-eslint/no-unsafe-function-type": "error",
                "no-unused-expressions": "error",
                "no-useless-constructor": "error",
                "@typescript-eslint/no-wrapper-object-types": "error",
                "no-throw-literal": "off",
                "@typescript-eslint/prefer-as-const": "error",
                "@typescript-eslint/prefer-literal-enum-member": "error",
                "@typescript-eslint/prefer-namespace-keyword": "error",
                "prefer-promise-reject-errors": "off",
                "require-await": "off",
                "@typescript-eslint/triple-slash-reference": "error",
                "@typescript-eslint/unified-signatures": "error",
                "@typescript-eslint/adjacent-overload-signatures": "error",
                "@typescript-eslint/array-type": "error",
                "@typescript-eslint/ban-tslint-comment": "error",
                "@typescript-eslint/class-literal-property-style": "error",
                "@typescript-eslint/consistent-generic-constructors": "error",
                "@typescript-eslint/consistent-indexed-object-style": "error",
                "@typescript-eslint/consistent-type-assertions": "error",
                "@typescript-eslint/consistent-type-definitions": "error",
                "@typescript-eslint/no-confusing-non-null-assertion": "error",
                "no-empty-function": "error",
                "@typescript-eslint/no-inferrable-types": "error",
                "@typescript-eslint/prefer-for-of": "error",
                "@typescript-eslint/prefer-function-type": "error",
                "react-hooks/rules-of-hooks": "error",
                "react-hooks/exhaustive-deps": "warn",
                "react/display-name": "error",
                "react/jsx-key": "error",
                "react/jsx-no-comment-textnodes": "error",
                "react/jsx-no-duplicate-props": "error",
                "react/jsx-no-target-blank": "error",
                "react/jsx-no-undef": "error",
                "react/no-children-prop": "error",
                "react/no-danger-with-children": "error",
                "react/no-direct-mutation-state": "error",
                "react/no-find-dom-node": "error",
                "react/no-is-mounted": "error",
                "react/no-render-return-value": "error",
                "react/no-string-refs": "error",
                "react/no-unescaped-entities": "error",
                "react/no-unknown-property": "error",
                "react/no-unsafe": "off",
                "react/react-in-jsx-scope": "off",
                "react/only-export-components": [
                    "warn",
                    { allowConstantExport: true },
                ],
            },
        },
    ],
};
