/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HistoryCompareImport } from './routes/history.compare'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const HistoryCompareRoute = HistoryCompareImport.update({
  id: '/history/compare',
  path: '/history/compare',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/history.compare.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/history/compare': {
      id: '/history/compare'
      path: '/history/compare'
      fullPath: '/history/compare'
      preLoaderRoute: typeof HistoryCompareImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/about': typeof AboutLazyRoute
  '/history/compare': typeof HistoryCompareRoute
}

export interface FileRoutesByTo {
  '/about': typeof AboutLazyRoute
  '/history/compare': typeof HistoryCompareRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/about': typeof AboutLazyRoute
  '/history/compare': typeof HistoryCompareRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/history/compare'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/history/compare'
  id: '__root__' | '/about' | '/history/compare'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AboutLazyRoute: typeof AboutLazyRoute
  HistoryCompareRoute: typeof HistoryCompareRoute
}

const rootRouteChildren: RootRouteChildren = {
  AboutLazyRoute: AboutLazyRoute,
  HistoryCompareRoute: HistoryCompareRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/about",
        "/history/compare"
      ]
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/history/compare": {
      "filePath": "history.compare.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
