name: Test and build

permissions:
    contents: read

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    lint-and-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Install pnpm
              uses: pnpm/action-setup@v5
            - name: Set up Node
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Lint
              run: pnpm run lint:check

            - name: Unit tests
              run: pnpm run test:unit

            - name: Build
              env:
                  # Upload source maps on every build
                  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
              run: pnpm run build

            - name: Check route tree is up to date
              run: |
                  if ! git diff --exit-code src/routeTree.gen.ts; then
                      echo "Error: The route tree file (src/routeTree.gen.ts) is not up to date."
                      echo "Run 'pnpm run build' and commit the changes."
                      exit 1
                  fi
                  echo "Route tree is up to date ✓"

    ui-tests:
        runs-on: ubuntu-latest
        container:
            # https://mcr.microsoft.com/en-us/artifact/mar/playwright/tags
            image: mcr.microsoft.com/playwright:v1.58.2-noble
            options: --ipc=host
        strategy:
            matrix:
                browser: [chromium, webkit]
            fail-fast: false
        steps:
            - uses: actions/checkout@v6
            - name: Install pnpm
              uses: pnpm/action-setup@v5
            - name: Set up Node
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Test
              run: pnpm run test:ui:${{ matrix.browser }}
